acme_tablero:
    resource: "@AcmeTableroBundle/Resources/config/routing.yml"
    prefix:   /
    
login:
    pattern: /login
    defaults: { _controller: AcmeTableroBundle:Security:login }
 
login_check:
    pattern: /login_check
 
logout:
    pattern: /logout

