parameters:
#    acme_tablero.example.class: Acme\TableroBundle\Example

services:
#    acme_tablero.example:
#        class: %acme_tablero.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
